apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-3c1e"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "myakscluster-3c1e"
  template:
    metadata:
      labels:
        app: "myakscluster-3c1e"
    spec:
      containers:
        - name: "myakscluster-3c1e"
          image: "akila.azurecr.io/myakscluster"
          ports:
          - containerPort: 3000
