apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-08b9"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-08b9"
  template:
    metadata:
      labels:
        app: "myakscluster-08b9"
    spec:
      containers:
        - name: "myakscluster-08b9"
          image: "akila.azurecr.io/myakscluster"
          ports:
          - containerPort: 3000