apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-3c1e"
    labels:
        app: "myakscluster-3c1e"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-3c1e"