apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-08b9"
    labels:
        app: "myakscluster-08b9"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-08b9"