on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag akilaliyanage/it19120362_ctse:${GITHUB_SHA}
    - name: push the image
      run: docker push akilaliyanage/it19120812_ctse:${GITHUB_SHA}

#     - name: Create ACR
#       id: create-acr
#       run: |
#         az acr create -n akila -g akila81dc-rg --location "Japan East" --sku Basic --admin-enabled
#         echo "::set-output name=acr_username::`az acr credential show -n akila --query username | xargs`"
#         echo "::set-output name=acr_password::`az acr credential show -n akila --query passwords[0].value | xargs`"
#         echo "::add-mask::`az acr credential show -n akila --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: hub.docker.com
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t akilaliyanage/it19120362_ctse:${GITHUB_SHA} --label dockerfile-path=Dockerfile
        docker push akilaliyanage/it19120362_ctse:${GITHUB_SHA}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclusteraa58 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclusteraa58`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclusteraa58
        container-registry-url: hub.docker.com
        container-registry-username: ${{secrets.DOCKER_USER}}
        container-registry-password: ${{secrets.DOCKER_PASSWORD}}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclusteraa58
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          akilaliyanage/it19120362-ctse:${GITHUB_SHA}
        imagepullsecrets: |
          myaksclusterdockerauth   
